# Generated by Django 4.2.4 on 2023-08-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHubApp', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
